"""Export/import as JSON, either the whole config ("Backup all", scope=all)
or one object type at a time (sites, devices, circuits, regions, settings)
from the Settings page. Per-object exports exist for two reasons: sharing
just one slice of config between environments, and — the bigger one —
surviving a schema change that breaks one part of the DB without losing
everything else. See CLAUDE.md's backup-compatibility rule and
schema_sync.py, which is the first line of defense (additive schema
changes should just self-heal); this is the fallback for when a change
genuinely can't be additive.

Deliberately excluded from every scope:
- Device credentials (SNMP community/keys, SSH password). Never decrypted
  or otherwise materialized here — see crypto.py's rule that credentials
  never travel in plaintext outside that module. Restoring always requires
  re-entering credentials per device (settings.html and the import route
  both surface this).
- User accounts, so a restore never locks the current session out.
- Derived telemetry (CircuitStatusHistory, AlertMute, UtilizationRollup,
  live interface counters, circuit debounce counts) — regenerated by the
  poller after restore rather than carried over from a stale snapshot.

Import is a full replace *of that scope's own table(s) only* — it never
cascades to related tables. Importing "sites" alone doesn't touch devices,
even though devices reference site_id; if you're rebuilding a wiped
database from scoped exports, import in dependency order: sites, then
devices, then circuits, then regions, then settings (any order relative
to each other). Preserves original ids so foreign keys resolve without a
remapping pass, same as the full backup always has.
"""
from datetime import datetime

from sitewatch.extensions import db
from sitewatch.models import (
    Site, Device, Interface, CircuitRole, Circuit, CircuitWaypoint, MapRegion, Setting,
    CircuitStatusHistory, AlertMute, UtilizationRollup,
)

FORMAT = "sitewatch-backup"
VERSION = 1

SCOPES = ("all", "sites", "devices", "circuits", "regions", "settings")

# Which top-level keys a file must have for a given scope, beyond format/version.
_SCOPE_KEYS = {
    "sites": {"sites"},
    "devices": {"devices", "interfaces"},
    "circuits": {"circuit_roles", "circuits"},
    "regions": {"regions"},
    "settings": {"settings"},
}
# "all" only strictly requires the sections that have existed since the very
# first backup format. "regions" is a newer, optional addition — an export
# from before MapRegion existed simply won't have it, and that must not be
# an import error (see CLAUDE.md's backup-compatibility rule; _load_regions
# already tolerates a missing key via .get("regions", [])).
_SCOPE_KEYS["all"] = {"sites", "devices", "interfaces", "circuit_roles", "circuits", "settings"}


class BackupImportError(Exception):
    pass


def _export_sites():
    return {"sites": [
        {"id": s.id, "name": s.name, "lat": s.lat, "lon": s.lon,
         "site_type": s.site_type, "netbox_id": s.netbox_id, "source": s.source}
        for s in Site.query.all()
    ]}


def _export_devices():
    return {
        "devices": [
            {
                "id": d.id, "site_id": d.site_id, "hostname": d.hostname,
                "mgmt_ip": d.mgmt_ip, "vendor": d.vendor,
                "snmp_version": d.snmp_version,
                "snmpv3_username": d.snmpv3_username,
                "snmpv3_auth_protocol": d.snmpv3_auth_protocol,
                "snmpv3_priv_protocol": d.snmpv3_priv_protocol,
                "ssh_username": d.ssh_username,
                "netbox_id": d.netbox_id, "source": d.source,
            }
            for d in Device.query.all()
        ],
        # Owned by devices (Device.interfaces cascades on delete) — exported
        # alongside them so a devices-only restore doesn't leave every
        # circuit dangling with no interfaces to point at.
        "interfaces": [
            {
                "id": i.id, "device_id": i.device_id, "if_index": i.if_index,
                "if_descr": i.if_descr, "if_alias": i.if_alias,
                "if_speed_bps": i.if_speed_bps,
            }
            for i in Interface.query.all()
        ],
    }


def _export_circuits():
    return {
        "circuit_roles": [{"id": r.id, "name": r.name, "tier": r.tier} for r in CircuitRole.query.all()],
        "circuits": [
            {
                "id": c.id, "name": c.name, "role_id": c.role_id,
                "parent_circuit_id": c.parent_circuit_id,
                "interface_a_id": c.interface_a_id,
                "interface_b_id": c.interface_b_id,
                "lag_interface_a_id": c.lag_interface_a_id,
                "lag_interface_b_id": c.lag_interface_b_id,
                "capacity_bps_override": c.capacity_bps_override,
                "waypoints": [{"site_id": w.site_id, "position": w.position} for w in c.waypoints],
            }
            for c in Circuit.query.all()
        ],
    }


def _export_regions():
    return {"regions": [
        {"id": r.id, "name": r.name, "center_lat": r.center_lat, "center_lon": r.center_lon, "zoom": r.zoom}
        for r in MapRegion.query.all()
    ]}


def _export_settings():
    return {"settings": {k: Setting.get(k) for k in Setting.DEFAULTS}}


_EXPORTERS = {
    "sites": _export_sites,
    "devices": _export_devices,
    "circuits": _export_circuits,
    "regions": _export_regions,
    "settings": _export_settings,
}


def export_data(scope="all"):
    if scope not in SCOPES:
        raise ValueError(f"Unknown backup scope: {scope!r}")
    payload = {"format": FORMAT, "version": VERSION, "scope": scope,
               "exported_at": datetime.utcnow().isoformat() + "Z"}
    scopes = _EXPORTERS.keys() if scope == "all" else [scope]
    for s in scopes:
        payload.update(_EXPORTERS[s]())
    return payload


def _validate(data, expected_scope):
    if not isinstance(data, dict):
        raise BackupImportError("File doesn't look like a Sensus SiteWatch backup.")
    if data.get("format") != FORMAT:
        raise BackupImportError("File doesn't look like a Sensus SiteWatch backup.")
    if data.get("version") != VERSION:
        raise BackupImportError(f"Unsupported backup version: {data.get('version')!r}.")
    file_scope = data.get("scope", "all")
    # A scope="all" file always contains every section, so it satisfies an
    # import into any single scope too (e.g. pulling just the sites back
    # out of a full backup) — only reject when the file is scoped AND it's
    # scoped to something other than what was asked for.
    if expected_scope != "all" and file_scope not in ("all", expected_scope):
        raise BackupImportError(f"This file is a '{file_scope}' export, not '{expected_scope}'.")
    if not _SCOPE_KEYS[expected_scope].issubset(data.keys()):
        raise BackupImportError("File doesn't look like a Sensus SiteWatch backup (missing expected sections).")


def _wipe_sites():
    Site.query.delete()


def _wipe_devices():
    Interface.query.delete()
    Device.query.delete()


def _wipe_circuits():
    CircuitStatusHistory.query.delete()
    AlertMute.query.delete()
    CircuitWaypoint.query.delete()
    Circuit.query.delete()
    CircuitRole.query.delete()


def _wipe_regions():
    MapRegion.query.delete()


def _load_sites(data):
    for s in data["sites"]:
        db.session.add(Site(
            id=s["id"], name=s["name"], lat=s["lat"], lon=s["lon"],
            site_type=s.get("site_type", "site"),
            netbox_id=s.get("netbox_id"), source=s.get("source", "manual"),
            out_of_sync=False,
        ))


def _load_devices(data):
    for d in data["devices"]:
        db.session.add(Device(
            id=d["id"], site_id=d["site_id"], hostname=d["hostname"],
            mgmt_ip=d["mgmt_ip"], vendor=d["vendor"],
            snmp_version=d.get("snmp_version", "v2c"),
            snmpv3_username=d.get("snmpv3_username"),
            snmpv3_auth_protocol=d.get("snmpv3_auth_protocol"),
            snmpv3_priv_protocol=d.get("snmpv3_priv_protocol"),
            ssh_username=d.get("ssh_username"),
            netbox_id=d.get("netbox_id"), source=d.get("source", "manual"),
            out_of_sync=False, reachable=True,
        ))
    for i in data["interfaces"]:
        db.session.add(Interface(
            id=i["id"], device_id=i["device_id"], if_index=i["if_index"],
            if_descr=i.get("if_descr"), if_alias=i.get("if_alias"),
            if_speed_bps=i.get("if_speed_bps"),
        ))


def _load_circuits(data):
    for r in data["circuit_roles"]:
        db.session.add(CircuitRole(id=r["id"], name=r["name"], tier=r["tier"]))
    for c in data["circuits"]:
        db.session.add(Circuit(
            id=c["id"], name=c["name"], role_id=c["role_id"],
            parent_circuit_id=c.get("parent_circuit_id"),
            interface_a_id=c.get("interface_a_id"),
            interface_b_id=c.get("interface_b_id"),
            # .get(), not [...] — an export from before these existed
            # simply won't have the keys, and that must not be an import
            # error (see CLAUDE.md's backup-compatibility rule).
            lag_interface_a_id=c.get("lag_interface_a_id"),
            lag_interface_b_id=c.get("lag_interface_b_id"),
            capacity_bps_override=c.get("capacity_bps_override"),
        ))
        for w in c.get("waypoints", []):
            db.session.add(CircuitWaypoint(circuit_id=c["id"], site_id=w["site_id"], position=w["position"]))


def _load_regions(data):
    for r in data.get("regions", []):
        db.session.add(MapRegion(
            id=r["id"], name=r["name"], center_lat=r["center_lat"],
            center_lon=r["center_lon"], zoom=r["zoom"],
        ))


def _load_settings(data):
    for k, v in data["settings"].items():
        if k in Setting.DEFAULTS:
            Setting.set(k, v)


_WIPE_AND_LOAD = {
    "sites": (_wipe_sites, _load_sites),
    "devices": (_wipe_devices, _load_devices),
    "circuits": (_wipe_circuits, _load_circuits),
    "regions": (_wipe_regions, _load_regions),
    "settings": (None, _load_settings),  # key/value upsert, nothing to wipe first
}


def import_data(data, scope="all"):
    if scope not in SCOPES:
        raise ValueError(f"Unknown backup scope: {scope!r}")
    _validate(data, scope)
    scopes = _WIPE_AND_LOAD.keys() if scope == "all" else [scope]
    try:
        for s in scopes:
            wipe, load = _WIPE_AND_LOAD[s]
            if wipe:
                wipe()
            load(data)
        db.session.commit()
    except KeyError as e:
        db.session.rollback()
        raise BackupImportError(f"Malformed backup: missing field {e}.")
    except BackupImportError:
        db.session.rollback()
        raise
    except Exception as e:
        db.session.rollback()
        raise BackupImportError(f"Import failed: {e}")
