"""Full-config export/import as a single JSON file — the "backup the whole
monitoring solution" feature. Covers sites, devices, interfaces, circuit
roles, circuits (including their cosmetic map waypoints), and settings.

Deliberately excluded:
- Device credentials (SNMP community/keys, SSH password). Never decrypted
  or otherwise materialized here — see crypto.py's rule that credentials
  never travel in plaintext outside that module. Restoring a backup always
  requires re-entering credentials per device (settings.html and the
  import route both surface this).
- User accounts, so a restore never locks the current session out.
- Derived telemetry (CircuitStatusHistory, AlertMute, UtilizationRollup,
  live interface counters, circuit debounce counts) — regenerated by the
  poller after restore rather than carried over from a stale snapshot.

Import is a full replace: existing config rows are wiped and reloaded from
the file, preserving original ids so foreign keys resolve without a
remapping pass.
"""
from datetime import datetime

from sitewatch.extensions import db
from sitewatch.models import (
    Site, Device, Interface, CircuitRole, Circuit, CircuitWaypoint, Setting,
    CircuitStatusHistory, AlertMute, UtilizationRollup,
)

FORMAT = "sitewatch-backup"
VERSION = 1

REQUIRED_KEYS = {"format", "version", "sites", "devices", "interfaces",
                  "circuit_roles", "circuits", "settings"}


class BackupImportError(Exception):
    pass


def export_data():
    return {
        "format": FORMAT,
        "version": VERSION,
        "exported_at": datetime.utcnow().isoformat() + "Z",
        "sites": [
            {
                "id": s.id, "name": s.name, "lat": s.lat, "lon": s.lon,
                "site_type": s.site_type,
                "netbox_id": s.netbox_id, "source": s.source,
            }
            for s in Site.query.all()
        ],
        "devices": [
            {
                "id": d.id, "site_id": d.site_id, "hostname": d.hostname,
                "mgmt_ip": d.mgmt_ip, "vendor": d.vendor,
                "snmp_version": d.snmp_version,
                "snmpv3_username": d.snmpv3_username,
                "snmpv3_auth_protocol": d.snmpv3_auth_protocol,
                "snmpv3_priv_protocol": d.snmpv3_priv_protocol,
                "ssh_username": d.ssh_username,
                "netbox_id": d.netbox_id, "source": d.source,
            }
            for d in Device.query.all()
        ],
        "interfaces": [
            {
                "id": i.id, "device_id": i.device_id, "if_index": i.if_index,
                "if_descr": i.if_descr, "if_alias": i.if_alias,
                "if_speed_bps": i.if_speed_bps,
            }
            for i in Interface.query.all()
        ],
        "circuit_roles": [
            {"id": r.id, "name": r.name, "tier": r.tier}
            for r in CircuitRole.query.all()
        ],
        "circuits": [
            {
                "id": c.id, "name": c.name, "role_id": c.role_id,
                "parent_circuit_id": c.parent_circuit_id,
                "interface_a_id": c.interface_a_id,
                "interface_b_id": c.interface_b_id,
                "capacity_bps_override": c.capacity_bps_override,
                "waypoints": [{"site_id": w.site_id, "position": w.position} for w in c.waypoints],
            }
            for c in Circuit.query.all()
        ],
        "settings": {k: Setting.get(k) for k in Setting.DEFAULTS},
    }


def _validate(data):
    if not isinstance(data, dict) or not REQUIRED_KEYS.issubset(data.keys()):
        raise BackupImportError(
            "File doesn't look like a Sensus SiteWatch backup (missing expected sections)."
        )
    if data.get("format") != FORMAT:
        raise BackupImportError("File doesn't look like a Sensus SiteWatch backup.")
    if data.get("version") != VERSION:
        raise BackupImportError(f"Unsupported backup version: {data.get('version')!r}.")


def _wipe():
    # Children before parents; SQLite FK enforcement is off in this app but
    # keep insert/delete order clean rather than relying on that.
    CircuitStatusHistory.query.delete()
    AlertMute.query.delete()
    UtilizationRollup.query.delete()
    CircuitWaypoint.query.delete()
    Circuit.query.delete()
    Interface.query.delete()
    Device.query.delete()
    Site.query.delete()
    CircuitRole.query.delete()


def _load(data):
    for s in data["sites"]:
        db.session.add(Site(
            id=s["id"], name=s["name"], lat=s["lat"], lon=s["lon"],
            site_type=s.get("site_type", "site"),
            netbox_id=s.get("netbox_id"), source=s.get("source", "manual"),
            out_of_sync=False,
        ))
    for d in data["devices"]:
        db.session.add(Device(
            id=d["id"], site_id=d["site_id"], hostname=d["hostname"],
            mgmt_ip=d["mgmt_ip"], vendor=d["vendor"],
            snmp_version=d.get("snmp_version", "v2c"),
            snmpv3_username=d.get("snmpv3_username"),
            snmpv3_auth_protocol=d.get("snmpv3_auth_protocol"),
            snmpv3_priv_protocol=d.get("snmpv3_priv_protocol"),
            ssh_username=d.get("ssh_username"),
            netbox_id=d.get("netbox_id"), source=d.get("source", "manual"),
            out_of_sync=False, reachable=True,
        ))
    for i in data["interfaces"]:
        db.session.add(Interface(
            id=i["id"], device_id=i["device_id"], if_index=i["if_index"],
            if_descr=i.get("if_descr"), if_alias=i.get("if_alias"),
            if_speed_bps=i.get("if_speed_bps"),
        ))
    for r in data["circuit_roles"]:
        db.session.add(CircuitRole(id=r["id"], name=r["name"], tier=r["tier"]))
    for c in data["circuits"]:
        db.session.add(Circuit(
            id=c["id"], name=c["name"], role_id=c["role_id"],
            parent_circuit_id=c.get("parent_circuit_id"),
            interface_a_id=c.get("interface_a_id"),
            interface_b_id=c.get("interface_b_id"),
            capacity_bps_override=c.get("capacity_bps_override"),
        ))
        for w in c.get("waypoints", []):
            db.session.add(CircuitWaypoint(circuit_id=c["id"], site_id=w["site_id"], position=w["position"]))
    for k, v in data["settings"].items():
        if k in Setting.DEFAULTS:
            Setting.set(k, v)


def import_data(data):
    _validate(data)
    try:
        _wipe()
        _load(data)
        db.session.commit()
    except KeyError as e:
        db.session.rollback()
        raise BackupImportError(f"Malformed backup: missing field {e}.")
    except BackupImportError:
        db.session.rollback()
        raise
    except Exception as e:
        db.session.rollback()
        raise BackupImportError(f"Import failed: {e}")
